rm /home/pi/src/pele/output/*.wav

#python3 melodies/tune.py
python3 melodies/wed.py
#python3 melodies/vibes4u.py
python3 melodies/thu.py
python3 melodies/swi.py
python3 melodies/genevive.py
#python3 melodies/hoo.py
python3 melodies/fea.py
python3 melodies/beats.py
#python3 melodies/tune.py
#python3 melodies/cia.py
python3 melodies/mor.py
#python3 melodies/vibes2u.py
#python3 melodies/vale.py
python3 melodies/fie.py
#python3 melodies/holdingon.py
#python3 melodies/hoot.py
#python3 melodies/magpie.py
python3 melodies/jun.py
python3 melodies/fas.py
python3 melodies/bey.py
python3 melodies/cop.py
python3 melodies/sun.py
python3 melodies/bea.py
python3 melodies/fas.py
python3 melodies/genevive.py
python3 melodies/jun.py
python3 melodies/jul.py
python3 melodies/thu.py
python3 melodies/wed.py
python3 melodies/cia.py
python3 melodies/hoo.py
python3 melodies/hto.py
python3 melodies/wai.py
python3 melodies/oud.py
python3 melodies/bey.py
python3 melodies/cop.py
python3 melodies/sun.py
python3 melodies/tie.py
python3 melodies/cle.py
